config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#search'
  get 'search', to: 'home#github_search'
  get 'search_item', to: 'home#github_search_item'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search
  end

  def github_search
    @results=GithubSearchService.call(params["search"], params[:page], nil)
    respond_to do |format|
      format.js { render 'search_results'}
    end
  end

  def github_search_item
    @results = GithubSearchService.call(params[:search], params[:page], params[:category])
    respond_to do |format|
      format.js { render 'search_results_item'}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_results.html.erb
<div class="container">
<div class="card-columns" >
  <% @results.each do |category, results| %>
    <div id = <%=category %> class="col-md-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Search results in <%= category %>

          <span class="counter"><%= results.first[:total_count]  %></span></h5>
        </div>
        <ul class="list-group list-group-flush">
          <% results.first[:items].each do |item| %>

          <li class="list-group-item"><%=link_to item["login"] || item["title"] || item["full_name"], item['html_url'] %>
          <%= image_tag(item["avatar_url"] || item.try(:user).try(:avatar_url) || item.try("owner").try("avatar_url"), class: "avatar avatar-16 img-circle")%>

          </li>

          <% end %>
        </ul>
        <% params[:page]= params[:page] || 1 %>
        <div class="card-body">
          <nav aria-label="Page navigation example">
            <ul class="pagination">

              <% unless params[:page]== 1 %>
                <li class="page-item"><%= link_to "Prev", search_item_path(category: category, search: params["search"], page: params[:page].to_i-1), class:'page-link', remote: true %></li>
              <% end %>
              <% if results.last.to_i > params[:page].to_i %>
                <li class="page-item"><%= link_to "Next", search_item_path(category: category, search: params["search"], page: params[:page].to_i+1), class:'page-link', remote: true %></li>
                </br>
              <% end  %>
            </ul>
            <% unless params[:page] == 0 || results.last.to_i == 0 %>
              <div> Page <%=params[:page]  %> of <%=results.last.to_i  %></div>
            <% end %>
          </nav>
        </div>
      </div>
    </div>
  <% end %>

</div>
</div>

app/views/home/search.html.erb
<div class="container">
  <div class="loader"></div>
  <div class=row">
      <div class="search">
        <%= form_tag(search_path, method: "get", remote: true, class: "searchForm") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search here...", class: "searchTerm", required: true %>
          <button type="submit" class="searchButton">
            <i class="fa fa-search"></i>
          </button>
        <% end %>
    </div>
  </div>

  <div class="row">
    <div id="search-results">
    </div>
  </div>
</div>

app/views/home/search_results.js.erb
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");
$('.loader').hide();

app/views/home/search_results_item.js.erb
$(<%= @results.first.first %>).html("<%= escape_javascript(render :partial => 'results') %>");
$('.loader').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>